# Generated by Django 3.1.5 on 2021-03-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.FloatField()),
                ('name', models.CharField(max_length=32)),
                ('data', models.CharField(max_length=32)),
            ],
        ),
    ]
