# Generated by Django 3.1.5 on 2021-04-04 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_native',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.FloatField()),
                ('name', models.CharField(max_length=64)),
                ('data', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='user_part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.FloatField()),
                ('name', models.CharField(max_length=64)),
                ('data', models.CharField(max_length=64)),
                ('p', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
